[phases.setup]
nixPkgs = ["python311", "cairo", "pango", "gdk-pixbuf", "libffi"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python ULTIMATE_JE.py"
